name: Alaska Fare Map Interactive

on:
  workflow_dispatch:
  #schedule:
    #- cron: "0 6 * * *"

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up environment
        run: sudo apt-get update && sudo apt-get install -y jq curl

      - name: Generate Fare Map Interactive
        env:
          API_NINJAS_KEY: ${{ secrets.API_NINJAS_KEY }}   # for airport metadata
        run: |
          chmod +x generate_fares.sh
          bash ./generate_fares.sh

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Update interactive fare map [skip ci]" || echo "No changes"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
