name: Flight Tracker

on:
  workflow_dispatch:   # manual trigger
  #schedule:
    #- cron: "0 * * * *" # every hour

permissions:
  contents: write      # allow committing
  pages: write         # allow deploying to GitHub Pages
  id-token: write      # required by deploy-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}   # ensures push works

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq curl

      - name: Generate Flight Map
        run: bash ./generate_flights.sh

      - name: Commit & Push (for repo history)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Update flight map [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .   # include repo root, index.html must be here

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
